demo01/assets/scripts/jellyfish/jellyfish.js

fix jellyfish lerp bug

---

demo02/assets/scenes/ambient.scene
demo02/assets/scenes/ambient.scene.meta
demo02/assets/scenes/audio.scene
demo02/assets/scenes/shadows.scene

add simple ambient scene for example & doc-3d

add simple ambient scene for example & doc-3d

---

demo02/assets/scripts/collision-detection/engine-info.js

https://github.com/cocos-creator/3d-tasks/issues/1488

rename BUILT_IN to BUILTIN

---

demo01/assets/scenes/helmet.scene
demo01/assets/scenes/helmet.scene.meta
demo01/assets/scenes/knight.scene
demo01/assets/scenes/knight.scene.meta
demo01/assets/scenes/particle-compare.scene
demo01/assets/scenes/particle-compare.scene.meta
demo01/assets/scenes/sponza.scene
demo01/assets/scenes/sponza.scene.meta
demo02/assets/scenes/audio.scene
demo02/assets/scenes/audio.scene.meta
demo02/assets/scenes/blade-strom.scene
demo02/assets/scenes/blade-strom.scene.meta
demo02/assets/scenes/collision-detection.scene
demo02/assets/scenes/collision-detection.scene.meta
demo02/assets/scenes/custom-effect.scene
demo02/assets/scenes/custom-effect.scene.meta
demo02/assets/scenes/heal-spell.scene
demo02/assets/scenes/heal-spell.scene.meta
demo02/assets/scenes/particles.scene
demo02/assets/scenes/particles.scene.meta
demo02/assets/scenes/pbr.scene
demo02/assets/scenes/pbr.scene.meta
demo02/assets/scripts/TypeScript of skill-effect/self-destory.ts

RE: https://github.com/cocos-creator/3d-tasks/issues/1496
RE: https://github.com/cocos-creator/3d-tasks/issues/1490

add scene change

---

simple-fps/assets/PhysicsConfig.ts
simple-fps/assets/PhysicsConfig.ts.meta
simple-fps/assets/start.scene
simple-fps/assets/start.scene.meta

https://github.com/cocos-creator/3d-tasks/issues/1564

add physics environment condition for simple fps project

---

demo01/assets/scenes/sponza.scene
demo01/assets/scenes/tangents.scene
demo01/assets/scenes/winter.scene

RE: https://github.com/cocos-creator/3d-tasks/issues/1596
RE: https://github.com/cocos-creator/3d-tasks/issues/1591

scene change update

---

demo01/assets/scripts/jellyfish/jellyfish.js
demo01/assets/scripts/scenechange.js

RE： https://github.com/cocos-creator/3d-tasks/issues/1591

skip sponza on WeChat

---

wx-open-data-project/assets/ReadMe.md

https://github.com/cocos-creator/3d-tasks/issues/1748

add  readme in wx open data project

---

wx-open-data-project/assets/openData.scene
wx-open-data-project/assets/openData.scene.meta

Re: https://github.com/cocos-creator/3d-tasks/issues/1805

wx-open-data-project Add widget

---

demo02/assets/scenes/physics.scene

Re: https://github.com/cocos-creator/3d-tasks/issues/1815

physics add tips

---

simple-car-game/assets/start.scene
simple-car-game/assets/start.scene.meta
simple-fps/assets/start.scene

RE: https://github.com/cocos-creator/3d-tasks/issues/2052

canvas clean flag bug fix

---

demo02/assets/scenes/audio.scene

RE: https://github.com/cocos-creator/3d-tasks/issues/2286

audio widget update

---

demo02/assets/scenes/testlist.scene

https://github.com/cocos-creator/3d-tasks/issues/2287

set backRoot canvas priority to 10

---

roll-a-ball/assets/Roll a ball.scene
roll-a-ball/assets/TypeScript/ball-control.ts

https://github.com/cocos-creator/3d-tasks/issues/2317

add touch event for mobile device

---

planar-reflection/profiles/packages/engine.json

RE: https://github.com/cocos-creator/3d-tasks/issues/2534

planar-reflection renderpipeline set add

---

demo01/assets/scripts/testlist/backbutton.ts
demo01/assets/scripts/testlist/listitem.ts
demo02/assets/scripts/testlist/backbutton.ts
demo02/assets/scripts/testlist/listitem.ts

RE: https://github.com/cocos-creator/3d-tasks/issues/2651
RE: https://github.com/cocos-creator/3d-tasks/issues/2653

scene change bug fix

---

show-cases/assets/scenes/testlist.scene
show-cases/assets/scripts/testlist/backbutton.ts

Re：https://github.com/cocos-creator/3d-tasks/issues/2693

testlist update

---

simple-games/assets/simple-shooting/scenes/Main.scene

this issue will resolve https://github.com/cocos-creator/3d-tasks/issues/3502

add WidgetComponent to ui for simple-shooting

---

show-cases/assets/scenes/testlist.scene
show-cases/assets/scripts/testlist/backbutton.ts

RE: https://github.com/cocos-creator/3d-tasks/issues/3468
RE: https://github.com/cocos-creator/3d-tasks/issues/3476
RE: https://github.com/cocos-creator/3d-tasks/issues/2693

testlist bug fix

---

physics-3d/assets/demo/benchmark/scripts/Benchmark.ts

https://github.com/cocos-creator/3d-tasks/issues/3598
https://github.com/cocos-creator/3d-tasks/issues/3585
https://github.com/cocos-creator/3d-tasks/issues/3604

[physics-3d] optimize benchmark

---

physics-3d/assets/demo/benchmark/scripts/Benchmark.ts

https://github.com/cocos-creator/3d-tasks/issues/3695
https://github.com/cocos-creator/3d-tasks/issues/3689
https://github.com/cocos-creator/3d-tasks/issues/3585

[physics-3d] fix import math

---

physics-3d/assets/TestList.scene
physics-3d/assets/common/scripts/RaycastHelper.ts
physics-3d/assets/demo/benchmark/scripts/Benchmark.ts
physics-3d/assets/demo/simple-hole/scripts/gameplay/MotionCtr.ts

https://github.com/cocos-creator/3d-tasks/issues/4319
https://github.com/cocos-creator/3d-tasks/issues/4313
https://github.com/cocos-creator/3d-tasks/issues/4287

1.2 physics tweaks

---

show-cases/assets/meshes/sintel/sintel-01.FBX.meta
show-cases/assets/scripts/ad-hoc/exposure.ts

Re: https://github.com/cocos-creator/3d-tasks/issues/4317, https://github.com/cocos-creator/3d-tasks/issues/4301

fixed blade-storm and helmet

---

physics-3d/assets/cases/scenes/case-constraint-hinge.scene
physics-3d/assets/cases/scenes/case-constraint-p2p.scene
physics-3d/assets/cases/scenes/case-convex-colliders.scene
physics-3d/assets/cases/scenes/case-convex-colliders.scene.meta
physics-3d/assets/cases/scenes/case-group-mask.scene
physics-3d/assets/cases/scripts/GroupMaskTest.ts
physics-3d/assets/cases/scripts/RaycastTest.ts
physics-3d/assets/common/models/convex-hull/ch0.gltf
physics-3d/assets/common/models/convex-hull/ch0.gltf.meta
physics-3d/assets/demo/benchmark/demo-benchmark.scene
physics-3d/assets/demo/simple-hole/demo-simple-hole.scene
physics-3d/assets/demo/simple-hole/scripts/gameplay/Instantiate.ts
physics-3d/assets/experiment/character-controller/ep-character-controller.scene
physics-3d/assets/experiment/constraint/scenes/ep-constraint-hinge.scene
physics-3d/assets/experiment/constraint/scenes/ep-constraint-p2p.scene

https://github.com/cocos-creator/3d-tasks/issues/4323

[physics-3d] tweaks of group mask

---

physics-3d/assets/demo/benchmark/demo-benchmark.scene
physics-3d/assets/demo/benchmark/demo-benchmark.scene.meta
physics-3d/assets/demo/benchmark/scripts/Benchmark.ts
physics-3d/assets/demo/benchmark/scripts/Benchmark.ts.meta

https://github.com/cocos-creator/performance-tests-3d/pull/6

let maxSubSteps default to 1

---

physics-3d/assets/common/models/convex-hull.meta
physics-3d/assets/common/models/truck/Materials_truck02.FBX/Material #28.mtl

https://github.com/cocos-creator/3d-tasks/issues/4441

[physics-3d] fix material #28

---

planar-reflection/assets/planar-reflection.scene

https://github.com/cocos-creator/3d-tasks/issues/3831
https://github.com/cocos-creator/3d-tasks/issues/3833
https://github.com/cocos-creator/3d-tasks/issues/3851

repair planar shadow Invisible

---

show-cases/assets/scripts/unlit-quad.ts

RE:  https://github.com/cocos-creator/3d-tasks/issues/5151

effect name change

---

show-cases/assets/scenes/shadows.scene
show-cases/assets/scenes/shadows.scene.meta

https://github.com/cocos-creator/3d-tasks/issues/5249

update shadows scene

---

show-cases/assets/scenes/jellyfish.scene
show-cases/assets/scenes/jellyfish.scene.meta
show-cases/assets/scenes/pbr.scene
show-cases/assets/scenes/pbr.scene.meta
show-cases/assets/scenes/toon.scene
show-cases/assets/scenes/toon.scene.meta

RE： https://github.com/cocos-creator/3d-tasks/issues/5368

camera fix

---

show-cases/assets/prefabs/healspell/HealSpell.prefab

Re: https://github.com/cocos-creator/3d-tasks/issues/5581

fixed particle issue(5581)

---

show-cases/assets/scripts/audio/audio.ts

re: https://github.com/cocos-creator/3d-tasks/issues/5200

register 'started' event at the 'onLoad' phase

---

planar-reflection/assets/ReflectPlane.ts
planar-reflection/assets/planar-reflect-forward.rpp

https://github.com/cocos-creator/3d-tasks/issues/6561

Removal of deprecated interfaces

---

physics-3d/assets/cases/scripts/SupportPhyiscs.ts

https://github.com/cocos-creator/3d-tasks/issues/7019

[physics] fix logic

---

physics-3d/settings/v2/packages/project.json

fix: https://github.com/cocos-creator/3d-tasks/issues/7281

fitWidth for physics-3d project

---

show-cases/assets/prefabs/light-hint/light-hint.ts

color->mainColor
Closed cocos-creator/3d-tasks#7251

fix bug:property name

---

physics-3d/assets/demo/benchmark/scripts/Benchmark.ts
physics-3d/assets/demo/falling-ball/scripts/GameConfig.ts

https://github.com/cocos-creator/3d-tasks/issues/7722
https://github.com/cocos-creator/3d-tasks/issues/7550

fix reset config when change scene

---

npm-case/assets/Scripts/Bar.ts
npm-case/assets/Scripts/Bar.ts.meta
npm-case/assets/Scripts/BarMapped.ts
npm-case/assets/Scripts/BarMapped.ts.meta
npm-case/assets/Scripts/Foo.ts
npm-case/assets/Scripts/Foo.ts.meta
npm-case/assets/Scripts/Test.ts.meta
npm-case/assets/Scripts/TestImportMap.ts
npm-case/assets/Scripts/TestImportMap.ts.meta
npm-case/import-map.json

https://github.com/cocos-creator/3d-tasks/issues/7981

Import map demo

---

show-cases/assets/effects/skin.effect

https://github.com/cocos-creator/3d-tasks/issues/8329

fix unexpected shading effect on metal and vulkan

---

show-cases/assets/scripts/custom-effect/tunnel.ts

re: https://github.com/cocos-creator/3d-tasks/issues/8324
changeLog:
- 移除 eventManager 的使用

remove usage of eventManager

---

show-cases/assets/scenes/instanced-skinning-lighting.scene
show-cases/assets/scenes/instanced-skinning.scene

RE：https://github.com/cocos-creator/3d-tasks/issues/8485
RE：https://github.com/cocos-creator/example-3d/pull/167 cause this

fix scene camera Rect bug 

---

show-cases/assets/scripts/first-person-camera.ts

https://github.com/cocos-creator/3d-tasks/issues/8642

remove macro.KEY

---

simple-games/assets/simple-shooting/scripts/ShootingPlayerController.ts

https://github.com/cocos-creator/3d-tasks/issues/8388
在 simple shooting 测试例里禁用 mouse-move 事件

ban registering mouse moving event

---

physics-3d/assets/cases/scripts/RaycastTest.ts
physics-3d/assets/common/scripts/RaycastHelper.ts
protobuf/assets/scripts/Guy.ts
simple-games/assets/lobby/scripts/LobbyManager.ts

https://github.com/cocos-creator/3d-tasks/issues/8865

use Ray instead

---

physics-3d/assets/demo/buoyancy/demo-buoyancy.scene

* https://github.com/cocos-creator/3d-tasks/issues/9924

fix-demo-buoyancy-shadow -v3.4.0

---

show-cases/assets/scenes/hdr-ldr.scene
show-cases/assets/scripts/hdr-ldr/SwitchHDR.ts

添加场景是否开启HDR提示

---

physics-3d/assets/common/effects/bonus-unlit.effect

https://github.com/cocos-creator/3d-tasks/issues/10249

连续的逻辑表达式拆成step，否则oppo手机可能不兼容

---

physics-3d/assets/demo/simple-bow/models/red_apple/textures/Apple_Baked_baseColor.png.meta
physics-3d/settings/v2/packages/cocos-service.json
physics-3d/settings/v2/packages/engine.json

Re: https://github.com/cocos/3d-tasks/issues/12374

fix MipFilter

---

show-cases/assets/prefabs/light-hint/light-hint.ts

set property should restrict type, otherwise should lint an error

set property with vec4

---

show-cases/assets/scripts/UI.ts
show-cases/assets/scripts/ad-hoc/exposure.ts
show-cases/assets/scripts/ad-hoc/instanced-skinning.ts
show-cases/assets/scripts/audio/audio-controller.ts
show-cases/assets/scripts/first-person-camera.ts
show-cases/assets/scripts/hdr-ldr/SwitchHDR.ts
show-cases/assets/scripts/physics/ground.ts
show-cases/assets/scripts/skin/SSS.ts
show-cases/assets/scripts/skin/label-modifier.ts
show-cases/assets/scripts/testlist/backbutton.ts
show-cases/assets/scripts/testlist/listitem.ts

https://github.com/cocos/3d-tasks/issues/12646

remove deprecated usage

---

show-cases/assets/scripts/unlit-quad.ts

Re: https://github.com/cocos/3d-tasks/issues/13137, https://github.com/cocos/3d-tasks/issues/12683

update material info, fix bug

---

physics-3d/assets/cases/scripts/RaycastTest.ts
physics-3d/assets/common/scripts/EmitBullet.ts
physics-3d/assets/common/scripts/RaycastHelper.ts
physics-3d/assets/common/scripts/first-person-camera.ts
physics-3d/assets/demo/benchmark/scripts/Benchmark.ts
physics-3d/assets/demo/buoyancy/WaterWaves.ts
physics-3d/assets/demo/falling-ball/scripts/ColumnCtr.ts
physics-3d/assets/demo/falling-ball/scripts/GameCtr.ts
physics-3d/assets/demo/roll-a-ball/scripts/ball-control.ts
physics-3d/assets/demo/simple-bow/scripts/RiggedBow.ts
physics-3d/assets/demo/simple-car/scripts/debug/MapLoaderTesing.ts
physics-3d/assets/demo/simple-car/scripts/gameplay/BonusMgr.ts
physics-3d/assets/demo/simple-car/scripts/gameplay/FourDirButtons.ts
physics-3d/assets/demo/simple-car/scripts/gameplay/MotorCom.ts
physics-3d/assets/demo/simple-hole/scripts/gameplay/Instantiate.ts
physics-3d/assets/demo/simple-hole/scripts/gameplay/MotionCtr.ts
physics-3d/assets/experiment/character-controller/BearingController.ts
physics-3d/assets/experiment/character-controller/CharacterController.ts
physics-3d/assets/experiment/character-controller/CharacterControllerTest.ts
physics-3d/assets/misc/TestList/backbutton.ts

https://github.com/cocos/3d-tasks/issues/13344

remove deprecated usage (#13344)

---

show-cases/assets/prefabs/particles/Particle-burst-circle.prefab
show-cases/assets/prefabs/particles/Particle-burst-circle.prefab.meta
show-cases/assets/prefabs/particles/Particle-fireflies.prefab
show-cases/assets/prefabs/particles/Particle-fireflies.prefab.meta
show-cases/assets/scenes/AnimationEmbeddedParticles.scene
show-cases/assets/scenes/particles_noise_test.scene

1. Update particle burst time in animationEmbeddedParticles test case for a better burst result. In this case, the burst can be triggered more often with the gun shooting animation.
2.  updated camera for particle_noise_test test scene for a better result.
3.  Updated particle_noise_test with more cases
https://user-images.githubusercontent.com/6600688/181408640-5dba5791-4e2a-4347-8205-a081eedc8bec.mp4

Update particle burst time for a better burst result

---

physics-3d/assets/demo/buoyancy/Buoyancy.ts
physics-3d/assets/demo/buoyancy/WaterWaves.ts

https://github.com/cocos/3d-tasks/issues/13374

fix add multiple MeshRender to the same node (#13374)

---

native-script-bridge/assets/Script/callNative.ts
native-script-bridge/assets/scene/JsbBridgeTest.scene
native-script-bridge/settings/v2/packages/engine.json

Remove download task as unnecessary task.

Fix wrong logic for start native-script-scene

---

protobuf/assets/scripts/Guy.ts

use input instead of systemEventType

Deprecated fix #13611

---

show-cases/assets/scripts/Joystick.ts

https://github.com/cocos/3d-tasks/issues/13857

use UITransform instead of UITransformComponent

---

physics-3d/assets/cases/scripts/CollisionTest.ts
physics-3d/assets/cases/scripts/TriggerTest.ts
protobuf/assets/scripts/Guy.ts

fix UITransformComponent and CanvasComponent
https://github.com/cocos/3d-tasks/issues/13857
https://github.com/cocos/3d-tasks/issues/13870

Deprecated fix version3

---

physics-3d/assets/cases/scenes/case-physics-curveCast.scene
physics-3d/assets/cases/scenes/case-physics-curveCast.scene.meta
physics-3d/assets/common/scripts/CurveCastHelper.ts
physics-3d/assets/common/scripts/CurveCastHelper.ts.meta

https://github.com/cocos/3d-tasks/issues/12218
https://github.com/cocos/cocos-engine/pull/13086

init case-physics-curveCast

---

physics-3d/assets/cases/scripts/SupportPhyiscs.ts
physics-3d/assets/demo/simple-bow/scripts/RiggedBow.ts
physics-3d/assets/misc/checks/PhysicsEnvCheck.ts

change deprecated function

---

physics-3d/assets/cases/scenes/case-physics-curveCast.scene
physics-3d/assets/cases/scenes/case-physics-curveCast.scene.meta
physics-3d/assets/common/scripts/CurveCastHelper.ts

https://github.com/cocos/3d-tasks/issues/14697
https://github.com/cocos/3d-tasks/issues/14746
https://github.com/cocos/3d-tasks/issues/14817

curveCast add more descriptions and performance optimization #14697

---

show-cases/assets/meshes/env/gltf/Materials_scene/birch_green_mat.mtl
show-cases/assets/meshes/env/gltf/Materials_scene/birch_green_mat.mtl.meta
show-cases/assets/meshes/env/gltf/Materials_scene/birch_yellow_mat.mtl
show-cases/assets/meshes/env/gltf/Materials_scene/birch_yellow_mat.mtl.meta
show-cases/assets/meshes/env/gltf/Materials_scene/grass_green_SC_mat.mtl
show-cases/assets/meshes/env/gltf/Materials_scene/grass_green_SC_mat.mtl.meta
show-cases/assets/meshes/env/gltf/Materials_scene/grass_yellowgreen_mat.mtl
show-cases/assets/meshes/env/gltf/Materials_scene/grass_yellowgreen_mat.mtl.meta

Re: https://github.com/cocos/3d-tasks/issues/14671
Correct the property meta info of several materials used by show-case.

correct material property

---

physics-3d/assets/demo/simple-bow/models/desert_house_01_free/Materials_scene/BLACK.mtl
physics-3d/assets/demo/simple-bow/models/desert_house_01_free/Materials_scene/BLACK.mtl.meta

Re: https://github.com/cocos/3d-tasks/issues/14774, https://github.com/cocos/3d-tasks/issues/14752
Correct the meta info of material properties of BLACK.mtl

correct material properties

---

physics-3d/assets/cases/scenes/case-physics-curveCast.scene
physics-3d/assets/common/scripts/CurveCastHelper.ts

curvecast demo modifies UI

---

physics-3d/assets/cases/scenes/case-contact-data.scene
physics-3d/assets/cases/scenes/case-contact-data.scene.meta
physics-3d/assets/common/scripts/ContactPointHelper.ts

optimize v8 performance for case-contact-data.scene

optimize user script performance

---

physics-3d/assets/cases/scenes/case-constraint-fixed.scene
physics-3d/assets/cases/scenes/case-constraint-fixed.scene.meta

use convex collider so that torus can be attached to dynamic body

use convex collider so that torus can be attached to dynamic body

---

npm-case/assets/Scripts/Test.ts
npm-case/assets/Scripts/Test.ts.meta

(cherry picked from commit 80b145620eb44a1e74733a51aa44483bfeb131fe)

fix npm run error on taobao

---

physics-3d/assets/cases/scenes/case-damping.scene
physics-3d/assets/cases/scenes/case-damping.scene.meta
physics-3d/assets/demo/buoyancy/demo-buoyancy.scene
physics-3d/assets/demo/buoyancy/demo-buoyancy.scene.meta

* Optimize demo-buoyancy shadow effect for v3.5
* update

Merge v3.5

---

physics-3d/assets/common/scripts/SweepHelper.ts

https://github.com/cocos/3d-tasks/issues/16670

[opt] physics-3d sweep performance optimization

---

npm-case/Libs/MGOBE_v1.3.8/MGOBE.d.ts

Re: https://github.com/cocos/3d-tasks/issues/16632

npm-case: fix type error

---

physics-3d/assets/common/scripts/ContactPointHelper.ts

Re #https://github.com/cocos/3d-tasks/issues/16680
fix contact data helper

fix contact-data helper

---

physics-3d/assets/cases/scenes/case-physics-sweep.scene

https://github.com/cocos/3d-tasks/issues/16894

tweak sweep demo UI

---

physics-3d/assets/cases/scripts/CharacterControllerTest.ts
physics-3d/assets/common/scripts/SweepHelper.ts

https://github.com/cocos/3d-tasks/issues/16670

[fix] sweep demo performance opt. cct onGround-->isGrounded
